name: build-and-release
on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install dependencies
      run: npm ci
    - name: Tests for Linux
      if: runner.os == 'Linux'
      run: xvfb-run -a npm test
    - name : Tests for Windows and macOS
      if: runner.os != 'Linux'
      run: npm test
    - name: Release and publish (Linux only)
      if: matrix.os == 'ubuntu-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: |
        npx semantic-release
        npm run deploy
